Repository DCNJ-Uket/Uket-BE, pull requests merged in 2024-05, with the labels that each got.

#6 [SVR-11] feat: 대학별 현재 진행중인 축제 조회 기능 추가
  application/ticket-app-api/build.gradle
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/EventApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/DevController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/EventController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/CurrentEventResponse.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/UniversityEventService.java
  application/ticket-app-api/src/main/resources/data.sql
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/controller/EventControllerTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/controller/UserControllerTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/UniversityEventServiceTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/UserRegisterServiceTest.java
  core/src/main/java/com/uket/core/exception/ErrorCode.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/AuthConfig.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/filter/JwtFilter.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/interceptor/AuthorizationExtractor.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/interceptor/LoginInterceptor.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/validator/TokenValidator.java
  domain/event-domain/build.gradle
  domain/event-domain/src/main/java/com/uket/domain/event/entity/Events.java
  domain/event-domain/src/main/java/com/uket/domain/event/exception/EventException.java
  domain/event-domain/src/main/java/com/uket/domain/event/repository/EventRepository.java
  domain/event-domain/src/main/java/com/uket/domain/event/service/EventService.java
  domain/event-domain/src/test/java/com/uket/domain/event/service/EventServiceTest.java
  domain/university-domain/src/main/java/com/uket/domain/university/entity/University.java
  domain/university-domain/src/main/java/com/uket/domain/university/service/UniversityService.java
  domain/university-domain/src/test/java/com/uket/domain/university/service/UniversityServiceTest.java
Labels: ✨ 기능 구현

#7 [SVR-17] fix: 회원 상세 정보 학교 이메일 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UserController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/request/UserRegisterRequest.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/UserRegisterService.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/controller/EventControllerTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/controller/UserControllerTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/UserRegisterServiceTest.java
  core/src/main/java/com/uket/core/exception/ErrorCode.java
  domain/university-domain/src/main/java/com/uket/domain/university/entity/University.java
  domain/university-domain/src/main/java/com/uket/domain/university/service/UniversityService.java
  domain/university-domain/src/test/java/com/uket/domain/university/service/UniversityServiceTest.java
  domain/user-domain/src/main/java/com/uket/domain/user/dto/CreateUserDetailsDto.java
  domain/user-domain/src/main/java/com/uket/domain/user/entity/UserDetails.java
  domain/user-domain/src/main/java/com/uket/domain/user/service/UserDetailsService.java
Labels: 🚨버그🚨, ✨ 기능 구현

#9 [SVR-19] hotfix: 로그인 및 회원가입 시, 반환되는 값 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/AuthApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UserApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/AuthController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UserController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/AuthResponse.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/AuthService.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/AuthConfig.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/register/IsRegistered.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/register/IsRegisteredArgumentResolver.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/dto/response/userinfo/GoogleUserInfoResponse.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/dto/response/userinfo/KakaoUserInfoResponse.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/dto/response/userinfo/OAuth2UserInfoResponse.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/util/OAuth2UserInfoManager.java
  domain/user-domain/src/main/java/com/uket/domain/user/dto/CreateUserDto.java
  domain/user-domain/src/main/java/com/uket/domain/user/entity/Users.java
  domain/user-domain/src/main/java/com/uket/domain/user/service/UserService.java
Labels: 🔥 핫픽스

#11 [SVR-20] docs: API별 Error Response 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/AuthApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UniversityApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UserApi.java
  core/src/main/java/com/uket/core/exception/ErrorCode.java
Labels: 📄 문서화

#12 [SVR-21] infra: Slack 에러 로깅 로직 추가
  README.md
  application/ticket-app-api/build.gradle
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/handler/WebExceptionHandler.java
  application/ticket-app-api/src/main/resources/application.yml
  application/ticket-app-api/src/test/resources/application.yml
  modules/slack/build.gradle
  modules/slack/src/main/java/com/uket/modules/slack/ApplicationListener.java
  modules/slack/src/main/java/com/uket/modules/slack/SlackGateway.java
  modules/slack/src/main/java/com/uket/modules/slack/dto/ErrorReportDto.java
Labels: ⚒️ 인프라

#14 [SVR-22] 이미지 관련 S3 URL 반환 로직 추가
  README.md
  application/ticket-app-api/build.gradle
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UniversityApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UniversityController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/CurrentEventResponse.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/UniversityResponse.java
  application/ticket-app-api/src/main/resources/application.yml
  application/ticket-app-api/src/test/resources/application.yml
  domain/event-domain/src/main/java/com/uket/domain/event/dto/BannerDto.java
  domain/event-domain/src/main/java/com/uket/domain/event/entity/Banner.java
  domain/event-domain/src/main/java/com/uket/domain/event/repository/BannerRepository.java
  modules/aws-s3/build.gradle
  modules/aws-s3/src/main/java/com/uket/modules/aws/s3/config/S3Config.java
  modules/aws-s3/src/main/java/com/uket/modules/aws/s3/properties/S3Properties.java
  modules/aws-s3/src/main/java/com/uket/modules/aws/s3/service/S3Service.java
Labels: ✨ 기능 구현

#16 hotfix: dev profile application.yml 설정 추가
  application/ticket-app-api/src/main/resources/application.yml
Labels: 🔥 핫픽스

#18 [SVR-24] 배너 조회 시, 배너 제목 같이 반환하도록 수정
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UniversityApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/EventController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UniversityController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/UniversityResponse.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/UserRegisterService.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/util/S3ImageUrlConverter.java
  application/ticket-app-api/src/main/resources/application.yml
  application/ticket-app-api/src/main/resources/data.sql
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/controller/UniversityControllerTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/UserRegisterServiceTest.java
  domain/event-domain/src/main/java/com/uket/domain/event/dto/BannerDto.java
  domain/event-domain/src/main/java/com/uket/domain/event/dto/ShowNameDto.java
  domain/event-domain/src/main/java/com/uket/domain/event/dto/TicketingDto.java
  domain/event-domain/src/main/java/com/uket/domain/event/entity/Banner.java
  domain/event-domain/src/main/java/com/uket/domain/event/repository/EventRepositoryCustomImpl.java
  domain/event-domain/src/main/java/com/uket/domain/event/repository/ShowRepository.java
  domain/event-domain/src/main/java/com/uket/domain/event/repository/TicketingRepository.java
  domain/event-domain/src/main/java/com/uket/domain/event/service/EventService.java
  domain/event-domain/src/main/java/com/uket/domain/event/service/ShowService.java
  domain/event-domain/src/main/java/com/uket/domain/event/service/TicketingService.java
  domain/event-domain/src/test/java/com/uket/domain/event/service/EventServiceTest.java
  domain/event-domain/src/test/java/com/uket/domain/event/service/ShowServiceTest.java
  domain/university-domain/src/main/java/com/uket/domain/university/dto/UniversityDto.java
  domain/university-domain/src/main/java/com/uket/domain/university/entity/University.java
  domain/university-domain/src/main/java/com/uket/domain/university/service/UniversityService.java
Labels: ♻️ 리팩터링, ✨ 기능 구현

#20 docs: ERD 추가
  README.md
Labels: 📄 문서화

#19 [SVR-25] feat: 유저 정보 조회 API 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UserApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UserController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/AuthResponse.java
  core/src/main/java/com/uket/core/exception/ErrorCode.java
  domain/user-domain/src/main/java/com/uket/domain/user/dto/UserInfoDto.java
  domain/user-domain/src/main/java/com/uket/domain/user/service/UserService.java
Labels: ✨ 기능 구현

#25 hotfix: Spring TimeZone설정
  application/ticket-app-api/Dockerfile
Labels: 🔥 핫픽스

#28 hotfix: Spring TimeZone설정 변경
  application/ticket-app-api/Dockerfile
  application/ticket-app-api/src/main/java/com/uket/TicketApiApplication.java
  application/ticket-app-api/src/main/resources/application.yml
Labels: 🔥 핫픽스

#27 [SVR-30] 회원가입 토큰 저장
  .gitignore
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/UserRegisterService.java
Labels: ✨ 기능 구현
