Repository DCNJ-Uket/Uket-BE, pull requests merged in 2024-06, with the labels that each got.

#31 [SVR-15] 예매된 티켓 조회 기능
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UserApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UserController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/TicketInfoService.java
  application/ticket-app-api/src/main/resources/data.sql
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/TicketInfoServiceTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/TicketingServiceTest.java
  application/ticket-app-api/src/test/resources/application.yml
  domain/event-domain/src/main/java/com/uket/domain/event/repository/ReservationRepository.java
  domain/event-domain/src/main/java/com/uket/domain/event/repository/ShowRepository.java
  domain/ticket-domain/build.gradle
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/entity/Ticket.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/enums/TicketStatus.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/repository/TicketRepository.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/service/TicketService.java
  domain/user-domain/src/main/java/com/uket/domain/user/repository/UserRepository.java
Labels: ✨ 기능 구현

#32 [SVR-33] feat: 티켓별 QR코드 조회 기능 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/TicketController.java
  application/ticket-app-api/src/main/resources/application.yml
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/controller/TicketControllerTest.java
  core/src/main/java/com/uket/core/exception/ErrorCode.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/entity/Ticket.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/repository/TicketRepository.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/service/TicketService.java
Labels: ✨ 기능 구현

#34 hotfix: lazy init 문제 해결
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/TicketInfoService.java
Labels: 🔥 핫픽스

#36 [SVR-34] feat: 티켓 상태명 한글화
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CheckTicketDto.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/enums/TicketStatus.java
Labels: ✨ 기능 구현

#37 [SVR-35] feat: 유저 정보 조회 시, 대학 이름 반환되도록 변경
  domain/user-domain/src/main/java/com/uket/domain/user/dto/UserInfoDto.java
  domain/user-domain/src/main/java/com/uket/domain/user/service/UserService.java
Labels: ✨ 기능 구현

#38 [SVR-8] feat: 학교 메일 인증 로직 추가
  application/ticket-app-api/build.gradle
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/config/EmailConfig.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/EmailApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/EmailController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/request/AuthCodeRequest.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/request/AuthEmailRequest.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/AuthEmailResponse.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/properties/EmailProperties.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/properties/SmtpProperties.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/MailService.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/UserAuthEmailService.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/util/RandomCodeGenerator.java
  application/ticket-app-api/src/main/resources/application.yml
  application/ticket-app-api/src/test/resources/application.yml
  core/src/main/java/com/uket/core/exception/ErrorCode.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/AuthConfig.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/SecurityConfig.java
  domain/university-domain/src/main/java/com/uket/domain/university/service/UniversityService.java
  domain/user-domain/src/main/java/com/uket/domain/user/repository/UserRepository.java
  domain/user-domain/src/main/java/com/uket/domain/user/service/UserService.java
  modules/token-redis/src/main/java/com/uket/modules/redis/config/RedisConfig.java
  modules/token-redis/src/main/java/com/uket/modules/redis/service/RedisUtil.java
Labels: ✨ 기능 구현

#35 [SVR-28] 예매 취소 기능
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/TicketApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/TicketController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/CancelTicketResponse.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/TicketInfoServiceTest.java
  application/ticket-app-api/src/test/java/com/uket/app/ticket/api/service/TicketServiceTest.java
  application/ticket-app-api/src/test/resources/application.yml
  core/src/main/java/com/uket/core/exception/ErrorCode.java
  domain/event-domain/src/main/java/com/uket/domain/event/entity/Reservation.java
  domain/ticket-domain/build.gradle
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/dto/CancelTicketDto.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/entity/Ticket.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/repository/TicketRepository.java
  domain/ticket-domain/src/main/java/com/uket/domain/ticket/service/TicketService.java
Labels: ✨ 기능 구현

#39 [SVR-36] docs: 메일 관련 API 설명 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/EmailApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/request/AuthCodeRequest.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/request/AuthEmailRequest.java
  core/src/main/java/com/uket/core/exception/ErrorCode.java
Labels: 📄 문서화

#40 [SVR-37] feat: 인증 가능한 대학 조회 API 추가
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/UniversityApi.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/controller/impl/UniversityController.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/dto/response/CertifiableUniversityResponse.java
  application/ticket-app-api/src/main/java/com/uket/app/ticket/api/service/CertificationService.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/AuthConfig.java
  domain/auth-domain/src/main/java/com/uket/domain/auth/config/SecurityConfig.java
  domain/university-domain/src/main/java/com/uket/domain/university/dto/UniversityDto.java
  domain/university-domain/src/main/java/com/uket/domain/university/service/UniversityService.java
Labels: ✨ 기능 구현

#41 hotfix: 인증 가능한 대학 조회 API 일반인 제외
  domain/university-domain/src/main/java/com/uket/domain/university/repository/UniversityRepository.java
  domain/university-domain/src/main/java/com/uket/domain/university/service/UniversityService.java
Labels: 🔥 핫픽스
